YOURPROJECTNAMEGOESHERE: MainWindow Class Reference
MainWindow Class Reference
#include <mainwindow.h>
Public Member Functions
MainWindow (QWidget *parent=0)
~MainWindow ()
Private Slots
void on_m_flockDensity_valueChanged (int arg1)
void on_m_resetFlock_clicked ()
void on_m_applyFlock_clicked ()
void on_m_addBoids_clicked ()
void on_m_removeBoids_clicked ()
void on_m_changeBoidSize_valueChanged (double arg1)
void on_m_changeFlockColour_clicked ()
void on_m_renderFlockWireframe_toggled (bool checked)
void on_m_obstaclePosX_valueChanged (double arg1)
void on_m_obstaclePosY_valueChanged (double arg1)
void on_m_obstaclePosZ_valueChanged (double arg1)
void on_m_obstacleSize_valueChanged (double arg1)
void on_m_obstacleColour_clicked ()
void on_m_obstacleWireframe_toggled (bool checked)
void on_m_simDistance_valueChanged (double arg1)
void on_m_simFlockDistance_valueChanged (double arg1)
void on_m_simCohesion_valueChanged (double arg1)
void on_m_simSeparation_valueChanged (double arg1)
void on_m_simAlignment_valueChanged (double arg1)
void on_m_backColour_clicked ()
void on_m_bboxSize_valueChanged (double arg1)
Private Attributes
Ui::MainWindow * m_ui
GLWindow * m_gl
our openGL widget
Detailed Description
Definition at line 12 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0) [explicit]
Definition at line 4 of file mainwindow.cpp.
References m_gl, and m_ui.
                                      :
    QMainWindow(parent),
    m_ui(new Ui::MainWindow)
{
    m_ui->setupUi(this);
    m_gl = new GLWindow(this);
    m_ui->s_mainWindowGridLayout->addWidget(m_gl, 0, 0 ,2, 1);
    this->setWindowTitle(QString("Swarm Flock"));
}
MainWindow::~MainWindow ()
Definition at line 16 of file mainwindow.cpp.
References m_ui.
{
    delete m_ui;
}
Member Function Documentation
void MainWindow::on_m_addBoids_clicked () [private, slot]
Definition at line 62 of file mainwindow.cpp.
References GLWindow::addBoidsToFlock(), GLWindow::getCurrentBoidSize(), m_gl, and m_ui.
{
    if (m_gl->getCurrentBoidSize() <= 1990)
    {
        m_ui->m_flockDensity->setValue(m_ui->m_flockDensity->value() + 10);
        m_gl->addBoidsToFlock();
        m_ui->m_applyFlock->setEnabled(false);
    }
}
void MainWindow::on_m_applyFlock_clicked () [private, slot]
Definition at line 46 of file mainwindow.cpp.
References GLWindow::applyFlock(), GLWindow::getCurrentBoidSize(), m_gl, and m_ui.
{
    m_gl->applyFlock(m_ui->m_flockDensity->value());
    m_ui->m_applyFlock->setEnabled(false);
    if (m_gl->getCurrentBoidSize() > 1990)
        m_ui->m_addBoids->setEnabled(false);
    else
        m_ui->m_addBoids->setEnabled(true);
    if (m_gl->getCurrentBoidSize() < 30)
        m_ui->m_removeBoids->setEnabled(false);
    else
        m_ui->m_removeBoids->setEnabled(true);
}
void MainWindow::on_m_backColour_clicked () [private, slot]
Definition at line 163 of file mainwindow.cpp.
References m_gl, and GLWindow::setBackgroundColour().
{
    QColor colour = QColorDialog::getColor();
    ngl::Colour c;
    c.set(colour.redF(), colour.greenF(), colour.blueF());
    m_gl->setBackgroundColour(c);
}
void MainWindow::on_m_bboxSize_valueChanged (double arg1) [private, slot]
Definition at line 171 of file mainwindow.cpp.
References m_gl, and GLWindow::setBBoxSize().
{
    ngl::Vector size;
    size.set(arg1, arg1, arg1);
    m_gl->setBBoxSize(size);
}
void MainWindow::on_m_changeBoidSize_valueChanged (double arg1) [private, slot]
Definition at line 82 of file mainwindow.cpp.
References m_gl, and GLWindow::setBoidSize().
{
    m_gl->setBoidSize(arg1);
}
void MainWindow::on_m_changeFlockColour_clicked () [private, slot]
Definition at line 87 of file mainwindow.cpp.
References m_gl, and GLWindow::setBoidColor().
{
    QColor colour = QColorDialog::getColor();
    m_gl->setBoidColor(colour);
}
void MainWindow::on_m_flockDensity_valueChanged (int arg1) [private, slot]
Definition at line 21 of file mainwindow.cpp.
References GLWindow::getCurrentBoidSize(), m_gl, and m_ui.
{
    if (arg1 != m_gl->getCurrentBoidSize() && arg1 != m_gl->getCurrentBoidSize())
        m_ui->m_applyFlock->setEnabled(true);
    else
        m_ui->m_applyFlock->setEnabled(false);
    if (m_gl->getCurrentBoidSize() > 1990)
        m_ui->m_addBoids->setEnabled(false);
    else
        m_ui->m_addBoids->setEnabled(true);
    if (m_gl->getCurrentBoidSize() < 10)
        m_ui->m_removeBoids->setEnabled(false);
    else
        m_ui->m_removeBoids->setEnabled(true);
}
void MainWindow::on_m_obstacleColour_clicked () [private, slot]
Definition at line 127 of file mainwindow.cpp.
References m_gl, and GLWindow::setObstacleColour().
{
    QColor colour = QColorDialog::getColor();
    m_gl->setObstacleColour(colour);
}
void MainWindow::on_m_obstaclePosX_valueChanged (double arg1) [private, slot]
Definition at line 98 of file mainwindow.cpp.
References m_gl, m_ui, and GLWindow::setObstaclePosition().
{
    ngl::Vector pos;
    pos.set(arg1, m_ui->m_obstaclePosY->value(), m_ui->m_obstaclePosZ->value());
    m_gl->setObstaclePosition(pos);
}
void MainWindow::on_m_obstaclePosY_valueChanged (double arg1) [private, slot]
Definition at line 106 of file mainwindow.cpp.
References m_gl, m_ui, and GLWindow::setObstaclePosition().
{
    ngl::Vector pos;
    pos.set(m_ui->m_obstaclePosX->value(), arg1, m_ui->m_obstaclePosZ->value());
    m_gl->setObstaclePosition(pos);
}
void MainWindow::on_m_obstaclePosZ_valueChanged (double arg1) [private, slot]
Definition at line 114 of file mainwindow.cpp.
References m_gl, m_ui, and GLWindow::setObstaclePosition().
{
    ngl::Vector pos;
    pos.set(m_ui->m_obstaclePosX->value(), m_ui->m_obstaclePosY->value(), arg1);
    m_gl->setObstaclePosition(pos);
}
void MainWindow::on_m_obstacleSize_valueChanged (double arg1) [private, slot]
Definition at line 122 of file mainwindow.cpp.
References m_gl, and GLWindow::setObstacleSize().
{
    m_gl->setObstacleSize(arg1);
}
void MainWindow::on_m_obstacleWireframe_toggled (bool checked) [private, slot]
Definition at line 133 of file mainwindow.cpp.
References m_gl, and GLWindow::setObstacleWireframe().
{
    m_gl->setObstacleWireframe(checked);
}
void MainWindow::on_m_removeBoids_clicked () [private, slot]
Definition at line 72 of file mainwindow.cpp.
References GLWindow::getCurrentBoidSize(), m_gl, m_ui, and GLWindow::removeBoidsFromFlock().
{
    if (m_gl->getCurrentBoidSize() > 30)
    {
        m_ui->m_flockDensity->setValue(m_ui->m_flockDensity->value() - 10);
        m_gl->removeBoidsFromFlock();
        m_ui->m_applyFlock->setEnabled(false);
    }
}
void MainWindow::on_m_renderFlockWireframe_toggled (bool checked) [private, slot]
Definition at line 93 of file mainwindow.cpp.
References m_gl, and GLWindow::setFlockWireframe().
{
    m_gl->setFlockWireframe(checked);
}
void MainWindow::on_m_resetFlock_clicked () [private, slot]
Definition at line 39 of file mainwindow.cpp.
References m_gl, m_ui, and GLWindow::resetFlock().
{
    m_ui->m_flockDensity->setValue(200);
    m_gl->resetFlock();
    m_ui->m_applyFlock->setEnabled(false);
}
void MainWindow::on_m_simAlignment_valueChanged (double arg1) [private, slot]
Definition at line 158 of file mainwindow.cpp.
References m_gl, and GLWindow::setSimAlignment().
{
    m_gl->setSimAlignment(arg1);
}
void MainWindow::on_m_simCohesion_valueChanged (double arg1) [private, slot]
Definition at line 148 of file mainwindow.cpp.
References m_gl, and GLWindow::setSimCohesion().
{
    m_gl->setSimCohesion(arg1);
}
void MainWindow::on_m_simDistance_valueChanged (double arg1) [private, slot]
Definition at line 138 of file mainwindow.cpp.
References m_gl, and GLWindow::setSimDistance().
{
    m_gl->setSimDistance(arg1);
}
void MainWindow::on_m_simFlockDistance_valueChanged (double arg1) [private, slot]
Definition at line 143 of file mainwindow.cpp.
References m_gl, and GLWindow::setSimFlockDistance().
{
    m_gl->setSimFlockDistance(arg1);
}
void MainWindow::on_m_simSeparation_valueChanged (double arg1) [private, slot]
Definition at line 153 of file mainwindow.cpp.
References m_gl, and GLWindow::setSimSeparation().
{
    m_gl->setSimSeparation(arg1);
}
Member Data Documentation
GLWindow* MainWindow::m_gl [private]
our openGL widget
Definition at line 67 of file mainwindow.h.
Ui::MainWindow* MainWindow::m_ui [private]
Definition at line 64 of file mainwindow.h.
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp