YOURPROJECTNAMEGOESHERE: GLWindow Class Reference
GLWindow Class Reference
the main glwindow widget for our flock application using NGL. put in this file
#include <GLWindow.h>
Public Member Functions
GLWindow (QWidget *_parent)
Constructor for GLWindow.
~GLWindow ()
dtor
int getCurrentBoidSize ()
GUI releated methods.
void resetFlock ()
void applyFlock (int size)
void addBoidsToFlock ()
void removeBoidsFromFlock ()
void setBoidSize (double size)
void setBoidColor (QColor colour)
void setFlockWireframe (bool value)
void setObstaclePosition (ngl::Vector position)
void setObstacleSize (double size)
void setObstacleColour (QColor colour)
void setObstacleWireframe (bool value)
void setSimDistance (double distance)
void setSimFlockDistance (double distance)
void setSimCohesion (double cohesion)
void setSimSeparation (double separation)
void setSimAlignment (double alignment)
void setBackgroundColour (ngl::Colour colour)
void setBBoxSize (ngl::Vector size)
Protected Member Functions
void loadMatricesToColourShader (ngl::TransformStack &_tx)
void loadMatricesToShader (ngl::TransformStack &_tx)
void initializeGL ()
The following methods must be implimented in the sub class this is called when the window is created.
void resizeGL (const int _w, const int _h)
this is called whenever the window is re-sized
void paintGL ()
this is the main gl drawing routine which is called whenever the window needs to be re-drawn
Private Member Functions
void mouseMoveEvent (QMouseEvent *_event)
this method is called every time a mouse is moved
void mousePressEvent (QMouseEvent *_event)
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
void mouseReleaseEvent (QMouseEvent *_event)
this method is called everytime the mouse button is released inherited from QObject and overridden here.
void wheelEvent (QWheelEvent *_event)
this method is called everytime the mouse wheel is moved inherited from QObject and overridden here.
void timerEvent (QTimerEvent *_event)
timer to change the sphere position by calling update()
Private Attributes
int m_spinXFace
used to store the x rotation mouse value
int m_spinYFace
used to store the y rotation mouse value
bool m_rotate
flag to indicate if the mouse button is pressed when dragging
bool m_translate
flag to indicate if the Right mouse button is pressed when dragging
int m_origX
the previous x mouse value
int m_origY
the previous y mouse value
int m_origXPos
the previous x mouse value for Position changes
int m_origYPos
the previous y mouse value for Position changes
ngl::Camera * m_cam
Our Camera.
ngl::TransformStack m_transformStack
transformation stack for the gl transformations etc
ngl::Vector m_modelPos
the model position for mouse movement
ngl::Light * m_light
a simple light use to illuminate the screen
ngl::BBox * bbox
a bounding box to have our boids collide and confine them within a designated space
Obstacle * obstacle
a sphere obstacle within the boid space
Flock * flock
a pointer to the flock class to have access to the methods
ngl::Colour m_backgroundColour
variable to store the GL Depth Color
int m_sphereUpdateTimer
bool m_animate
flag to indicate if animation is active or not
ngl::ShaderLib * m_shader
Detailed Description
the main glwindow widget for our flock application using NGL. put in this file
Definition at line 29 of file GLWindow.h.
Constructor & Destructor Documentation
GLWindow::GLWindow (QWidget * _parent)
Constructor for GLWindow.
Parameters:
[in] _parent the parent window to create the GL context in
Definition at line 32 of file GLWindow.cpp.
References m_animate, m_backgroundColour, m_rotate, m_sphereUpdateTimer, m_spinXFace, m_spinYFace, and obstacle.
    : QGLWidget( new CreateCoreGLContext(QGLFormat::defaultFormat()), _parent )
{
    obstacle = new Obstacle(ngl::Vector(12,30,0), 4.0);
    // set this widget to have the initial keyboard focus
    setFocus();
    // re-size the widget to that of the parent (in this case the GLFrame passed in on construction)
    this->resize(_parent->size());
    // Now set the initial GLWindow attributes to default values
    // Roate is false
    m_rotate=false;
    // mouse rotation values set to 0
    m_spinXFace = 0;
    m_spinYFace = 0;
    m_sphereUpdateTimer = startTimer(1000 / 60); //run at 60FPS
    m_animate = true;
    m_backgroundColour.set(0.6f, 0.6f, 0.6f, 1.0f);
}
GLWindow::~GLWindow ()
dtor
Definition at line 55 of file GLWindow.cpp.
References m_light.
{
    ngl::NGLInit *Init = ngl::NGLInit::instance();
    std::cout<<"Shutting down NGL, removing VAO's and Shaders\n";
    delete m_light;
    Init->NGLQuit();
}
Member Function Documentation
void GLWindow::addBoidsToFlock ()
Definition at line 80 of file GLWindow.cpp.
References Flock::addBoids(), and flock.
{
    flock->addBoids();
}
void GLWindow::applyFlock (int size)
Definition at line 74 of file GLWindow.cpp.
References flock, Flock::resetBoids(), and Flock::setFlockSize().
{
    flock->setFlockSize(size);
    flock->resetBoids();
}
int GLWindow::getCurrentBoidSize ()
GUI releated methods.
Definition at line 63 of file GLWindow.cpp.
References flock, and Flock::getFlockSize().
{
    return flock->getFlockSize();
}
void GLWindow::initializeGL () [protected]
The following methods must be implimented in the sub class this is called when the window is created.
Definition at line 172 of file GLWindow.cpp.
References bbox, flock, m_backgroundColour, m_cam, m_light, m_shader, and obstacle.
{
    glClearColor(m_backgroundColour.m_r, m_backgroundColour.m_g, m_backgroundColour.m_b, m_backgroundColour.m_a);
    // enable depth testing for drawing
    glEnable(GL_DEPTH_TEST);
    // we need to initialise the NGL lib, under windows and linux we also need to
    // initialise GLEW, under windows this needs to be done in the app as well
    // as the lib hence the WIN32 define
    ngl::NGLInit *Init = ngl::NGLInit::instance();
    Init->initGlew();
#ifdef WIN32
    glewInit(); // need a local glew init as well as lib one for windows
#endif
    // now to load the shader and set the values
    // grab an instance of shader manager
    m_shader = ngl::ShaderLib::instance();
    // we are creating a shader called Phong
    m_shader->createShaderProgram("Phong");
    // now we are going to create empty shaders for Frag and Vert
    m_shader->attachShader("PhongVertex",ngl::VERTEX);
    m_shader->attachShader("PhongFragment",ngl::FRAGMENT);
    // attach the source
    m_shader->loadShaderSource("PhongVertex","shaders/Phong.vs");
    m_shader->loadShaderSource("PhongFragment","shaders/Phong.fs");
    // compile the shaders
    m_shader->compileShader("PhongVertex");
    m_shader->compileShader("PhongFragment");
    // add them to the program
    m_shader->attachShaderToProgram("Phong","PhongVertex");
    m_shader->attachShaderToProgram("Phong","PhongFragment");
    // now bind the shader attributes for most NGL primitives we use the following
    // layout attribute 0 is the vertex data (x,y,z)
    m_shader->bindAttribute("Phong",0,"inVert");
    // attribute 1 is the UV data u,v (if present)
    m_shader->bindAttribute("Phong",1,"inUV");
    // attribute 2 are the normals x,y,z
    m_shader->bindAttribute("Phong",2,"inNormal");
    // now we have associated this data we can link the shader
    m_shader->linkProgramObject("Phong");
    // and make it active ready to load values
    (*m_shader)["Phong"]->use();
    // the shader will use the currently active material and light0 so set them
    ngl::Material m(ngl::GOLD);
    // load our material values to the shader into the structure material (see Vertex shader)
    m.loadToShader("material");
    // Now we will create a basic Camera from the graphics library
    // This is a static camera so it only needs to be set once
    // First create Values for the camera position
    ngl::Vector From(200,120,120);
    ngl::Vector To(0,0,0);
    ngl::Vector Up(0,1,0);
    // now load to our new camera
    m_cam= new ngl::Camera(From,To,Up,ngl::PERSPECTIVE);
    // set the shape using FOV 45 Aspect Ratio based on Width and Height
    // The final two are near and far clipping planes of 0.5 and 10
    m_cam->setShape(45,(float)720.0/576.0,0.05,350,ngl::PERSPECTIVE);
    m_shader->setShaderParam3f("viewerPos",m_cam->getEye().m_x,m_cam->getEye().m_y,m_cam->getEye().m_z);
    // now create our light this is done after the camera so we can pass the
    // transpose of the projection matrix to the light to do correct eye space
    // transformations
    ngl::Matrix iv=m_cam->getViewMatrix();
    iv.transpose();
    m_light = new ngl::Light(ngl::Vector(120,120,120,1),ngl::Colour(1,1,1,1),ngl::Colour(1,1,1,1),ngl::POINTLIGHT);
    m_light->setTransform(iv);
    // load these values to the shader as well
    m_light->loadToShader("light");
    m_shader->createShaderProgram("Colour");
    m_shader->attachShader("ColourVertex",ngl::VERTEX);
    m_shader->attachShader("ColourFragment",ngl::FRAGMENT);
    m_shader->loadShaderSource("ColourVertex","shaders/Colour.vs");
    m_shader->loadShaderSource("ColourFragment","shaders/Colour.fs");
    m_shader->compileShader("ColourVertex");
    m_shader->compileShader("ColourFragment");
    m_shader->attachShaderToProgram("Colour","ColourVertex");
    m_shader->attachShaderToProgram("Colour","ColourFragment");
    m_shader->bindAttribute("Colour",0,"inVert");
    m_shader->linkProgramObject("Colour");
    (*m_shader)["Colour"]->use();
    m_shader->setShaderParam4f("Colour",1,1,1,1);
    glEnable(GL_DEPTH_TEST); // for removal of hidden surfaces
    ngl::VAOPrimitives *prim=ngl::VAOPrimitives::instance();
    prim->createSphere("sphere",0.8,1);
    bbox = new ngl::BBox(ngl::Vector(0,0,0),120,120,120);
    bbox->setDrawMode(GL_LINE);
    flock = new Flock(bbox, obstacle);
}
void GLWindow::loadMatricesToColourShader (ngl::TransformStack & _tx) [protected]
Definition at line 301 of file GLWindow.cpp.
References m_cam.
{
    ngl::ShaderLib *shader=ngl::ShaderLib::instance();
    (*shader)["Colour"]->use();
    ngl::Matrix MV;
    ngl::Matrix MVP;
    ngl::Matrix M;
    ngl::Mat3x3 normalMatrix;
    normalMatrix=MV;
    normalMatrix.inverse();
    MV= _tx.getCurrAndGlobal().getMatrix()*m_cam->getViewMatrix() ;
    MVP=MV*m_cam->getProjectionMatrix();
    shader->setShaderParamFromMatrix("MVP",MVP);
    shader->setShaderParamFromMatrix("M",M);
}
void GLWindow::loadMatricesToShader (ngl::TransformStack & _tx) [protected]
Definition at line 281 of file GLWindow.cpp.
References m_cam.
{
    ngl::ShaderLib *shader=ngl::ShaderLib::instance();
    ngl::Matrix MV;
    ngl::Matrix MVP;
    ngl::Mat3x3 normalMatrix;
    ngl::Matrix M;
    M=_tx.getCurrAndGlobal().getMatrix();
    MV=  _tx.getCurrAndGlobal().getMatrix()*m_cam->getViewMatrix();
    MVP= M*m_cam->getVPMatrix(); //MV*m_cam->getProjectionMatrix();
    normalMatrix=MV;
    normalMatrix.inverse();
    //  shader->setShaderParamFromMatrix("MV",MV);
    shader->setShaderParamFromMatrix("MVP",MVP);
    //  shader->setShaderParamFromMat3x3("normalMatrix",normalMatrix);
    //  shader->setShaderParamFromMatrix("M",M);
}
void GLWindow::mouseMoveEvent (QMouseEvent * _event) [private]
this method is called every time a mouse is moved
Parameters:
_event the Qt Event structure
Definition at line 379 of file GLWindow.cpp.
References INCREMENT, m_modelPos, m_origX, m_origXPos, m_origY, m_origYPos, m_rotate, m_spinXFace, m_spinYFace, and m_translate.
{
    // note the method buttons() is the button state when event was called
    // this is different from button() which is used to check which button was
    // pressed when the mousePress/Release event is generated
    if(m_rotate && _event->buttons() == Qt::LeftButton)
    {
        int diffx=_event->x()-m_origX;
        int diffy=_event->y()-m_origY;
        m_spinXFace += (float) 0.5f * diffy;
        m_spinYFace += (float) 0.5f * diffx;
        m_origX = _event->x();
        m_origY = _event->y();
        updateGL();
    }
    // right mouse translate code
    else if(m_translate && _event->buttons() == Qt::RightButton)
    {
        int diffX = (int)(_event->x() - m_origXPos);
        int diffY = (int)(_event->y() - m_origYPos);
        m_origXPos=_event->x();
        m_origYPos=_event->y();
        m_modelPos.m_x += INCREMENT * diffX;
        m_modelPos.m_y -= INCREMENT * diffY;
        updateGL();
    }
}
void GLWindow::mousePressEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
Parameters:
_event the Qt Event structure
Definition at line 412 of file GLWindow.cpp.
References m_origX, m_origXPos, m_origY, m_origYPos, m_rotate, and m_translate.
{
    // this method is called when the mouse button is pressed in this case we
    // store the value where the maouse was clicked (x,y) and set the Rotate flag to true
    if(_event->button() == Qt::LeftButton)
    {
        m_origX = _event->x();
        m_origY = _event->y();
        m_rotate =true;
    }
    // right mouse translate mode
    else if(_event->button() == Qt::RightButton)
    {
        m_origXPos = _event->x();
        m_origYPos = _event->y();
        m_translate=true;
    }
}
void GLWindow::mouseReleaseEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is released inherited from QObject and overridden here.
Parameters:
_event the Qt Event structure
Definition at line 434 of file GLWindow.cpp.
References m_rotate, and m_translate.
{
    // this event is called when the mouse button is released
    // we then set Rotate to false
    if (_event->button() == Qt::LeftButton)
    {
        m_rotate=false;
    }
    // right mouse translate mode
    if (_event->button() == Qt::RightButton)
    {
        m_translate=false;
    }
}
void GLWindow::paintGL () [protected]
this is the main gl drawing routine which is called whenever the window needs to be re-drawn
Definition at line 326 of file GLWindow.cpp.
References bbox, Flock::draw(), flock, loadMatricesToShader(), m_cam, m_modelPos, m_spinXFace, m_spinYFace, m_transformStack, Obstacle::ObsDraw(), and obstacle.
{
    // clear the screen and depth buffer
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    // grab an instance of the shader manager
    ngl::ShaderLib *shader=ngl::ShaderLib::instance();
    (*shader)["Phong"]->use();
    //Rotation based on the mouse position for our global transform
    ngl::Transformation trans;
    ngl::Matrix rotX;
    ngl::Matrix rotY;
    // create the rotation matrices
    rotX.rotateX(m_spinXFace);
    rotY.rotateY(m_spinYFace);
    // multiply the rotations
    ngl::Matrix final=rotY*rotX;
    // add the translations
    final.m_m[3][0] = m_modelPos.m_x;
    final.m_m[3][1] = m_modelPos.m_y;
    final.m_m[3][2] = m_modelPos.m_z;
    // set this in the TX stack
    trans.setMatrix(final);
    m_transformStack.setGlobal(trans);
    (*shader)["Colour"]->use();
    loadMatricesToShader(m_transformStack);
    bbox->draw();
    flock->draw("Phong",m_transformStack,m_cam);
    {
        m_transformStack.pushTransform();
        {
            //m_transformStack.setCurrent(0,10,0);
            loadMatricesToShader(m_transformStack);
            obstacle->ObsDraw("Phong",m_transformStack,m_cam);
        }
        m_transformStack.popTransform();
    }
    {
        m_transformStack.pushTransform();
        {
            loadMatricesToShader(m_transformStack);
        }
        m_transformStack.popTransform();
    }
}
void GLWindow::removeBoidsFromFlock ()
Definition at line 85 of file GLWindow.cpp.
References flock, and Flock::removeBoids().
{
    flock->removeBoids();
}
void GLWindow::resetFlock ()
Definition at line 68 of file GLWindow.cpp.
References flock, Flock::resetBoids(), and Flock::setFlockSize().
{
    flock->setFlockSize(200);
    flock->resetBoids();
}
void GLWindow::resizeGL (const int _w, const int _h) [protected]
this is called whenever the window is re-sized
Parameters:
[in] _w the width of the resized window
[in] _h the height of the resized window
Definition at line 269 of file GLWindow.cpp.
References m_cam.
{
    // set the viewport for openGL
    glViewport(0,0,_w,_h);
    // now set the camera size values as the screen size has changed
    m_cam->setShape(45,(float)_w/_h,0.05,350,ngl::PERSPECTIVE);
}
void GLWindow::setBackgroundColour (ngl::Colour colour)
Definition at line 156 of file GLWindow.cpp.
References m_backgroundColour.
{
    m_backgroundColour = colour;
    glClearColor(m_backgroundColour.m_r, m_backgroundColour.m_g, m_backgroundColour.m_b, m_backgroundColour.m_a);
}
void GLWindow::setBBoxSize (ngl::Vector size)
Definition at line 162 of file GLWindow.cpp.
References bbox.
{
    delete bbox;
    bbox = new ngl::BBox(ngl::Vector(0,0,0), size.m_x, size.m_y, size.m_z);
}
void GLWindow::setBoidColor (QColor colour)
Definition at line 95 of file GLWindow.cpp.
References flock, and Flock::setColour().
{
    ngl::Colour colourToSet;
    colourToSet.set(colour.redF(), colour.greenF(), colour.blueF());
    flock->setColour(colourToSet);
}
void GLWindow::setBoidSize (double size)
Definition at line 90 of file GLWindow.cpp.
References flock, and Flock::setBoidSize().
{
    flock->setBoidSize(size);
}
void GLWindow::setFlockWireframe (bool value)
Definition at line 103 of file GLWindow.cpp.
References flock, and Flock::setWireframe().
{
    flock->setWireframe(value);
}
void GLWindow::setObstacleColour (QColor colour)
Definition at line 118 of file GLWindow.cpp.
References obstacle, and Obstacle::setColour().
{
    ngl::Colour colourToSet;
    colourToSet.set(colour.redF(), colour.greenF(), colour.blueF());
    obstacle->setColour(colourToSet);
}
void GLWindow::setObstaclePosition (ngl::Vector position)
Definition at line 108 of file GLWindow.cpp.
References obstacle, and Obstacle::setSpherePosition().
{
    obstacle->setSpherePosition(position);
}
void GLWindow::setObstacleSize (double size)
Definition at line 113 of file GLWindow.cpp.
References obstacle, and Obstacle::setSphereRadius().
{
    obstacle->setSphereRadius(size);
}
void GLWindow::setObstacleWireframe (bool value)
Definition at line 126 of file GLWindow.cpp.
References obstacle, and Obstacle::setWireframe().
{
    obstacle->setWireframe(value);
}
void GLWindow::setSimAlignment (double alignment)
Definition at line 151 of file GLWindow.cpp.
References flock, and Flock::setSimAlignment().
{
    flock->setSimAlignment(alignment);
}
void GLWindow::setSimCohesion (double cohesion)
Definition at line 141 of file GLWindow.cpp.
References flock, and Flock::setSimCohesion().
{
    flock->setSimCohesion(cohesion);
}
void GLWindow::setSimDistance (double distance)
Definition at line 131 of file GLWindow.cpp.
References flock, and Flock::setSimDistance().
{
    flock->setSimDistance(distance);
}
void GLWindow::setSimFlockDistance (double distance)
Definition at line 136 of file GLWindow.cpp.
References flock, and Flock::setSimFlockDistance().
{
    flock->setSimFlockDistance(distance);
}
void GLWindow::setSimSeparation (double separation)
Definition at line 146 of file GLWindow.cpp.
References flock, and Flock::setSimSeparation().
{
    flock->setSimSeparation(separation);
}
void GLWindow::timerEvent (QTimerEvent * _event) [private]
timer to change the sphere position by calling update()
Definition at line 475 of file GLWindow.cpp.
References flock, m_animate, m_sphereUpdateTimer, and Flock::update().
{
    if(_event->timerId() == m_sphereUpdateTimer)
    {
        if (m_animate !=true)
        {
            return;
        }
        flock->update();
        updateGL();
    }
}
void GLWindow::wheelEvent (QWheelEvent * _event) [private]
this method is called everytime the mouse wheel is moved inherited from QObject and overridden here.
Parameters:
_event the Qt Event structure
Definition at line 451 of file GLWindow.cpp.
References m_modelPos, and ZOOM.
{
    // check the diff of the wheel position (0 means no change)
    if(_event->delta() > 0)
    {
        m_modelPos.m_z+=ZOOM;
    }
    else if(_event->delta() <0 )
    {
        m_modelPos.m_z-=ZOOM;
    }
    updateGL();
    ngl::Vector v;
    v.set(0, 0, 0);
    ngl::Vector direction;
    direction.set(0, 0.1, 0);
    v += direction;
}
Member Data Documentation
ngl::BBox* GLWindow::bbox [private]
a bounding box to have our boids collide and confine them within a designated space
Definition at line 126 of file GLWindow.h.
Flock* GLWindow::flock [private]
a pointer to the flock class to have access to the methods
Definition at line 133 of file GLWindow.h.
bool GLWindow::m_animate [private]
flag to indicate if animation is active or not
Definition at line 214 of file GLWindow.h.
ngl::Colour GLWindow::m_backgroundColour [private]
variable to store the GL Depth Color
Definition at line 136 of file GLWindow.h.
ngl::Camera* GLWindow::m_cam [private]
Our Camera.
Definition at line 110 of file GLWindow.h.
ngl::Light* GLWindow::m_light [private]
a simple light use to illuminate the screen
Definition at line 122 of file GLWindow.h.
ngl::Vector GLWindow::m_modelPos [private]
the model position for mouse movement
Definition at line 118 of file GLWindow.h.
int GLWindow::m_origX [private]
the previous x mouse value
Definition at line 94 of file GLWindow.h.
int GLWindow::m_origXPos [private]
the previous x mouse value for Position changes
Definition at line 102 of file GLWindow.h.
int GLWindow::m_origY [private]
the previous y mouse value
Definition at line 98 of file GLWindow.h.
int GLWindow::m_origYPos [private]
the previous y mouse value for Position changes
Definition at line 106 of file GLWindow.h.
bool GLWindow::m_rotate [private]
flag to indicate if the mouse button is pressed when dragging
Definition at line 86 of file GLWindow.h.
ngl::ShaderLib* GLWindow::m_shader [private]
Definition at line 216 of file GLWindow.h.
int GLWindow::m_sphereUpdateTimer [private]
Definition at line 210 of file GLWindow.h.
int GLWindow::m_spinXFace [private]
used to store the x rotation mouse value
Definition at line 78 of file GLWindow.h.
int GLWindow::m_spinYFace [private]
used to store the y rotation mouse value
Definition at line 82 of file GLWindow.h.
ngl::TransformStack GLWindow::m_transformStack [private]
transformation stack for the gl transformations etc
Definition at line 114 of file GLWindow.h.
bool GLWindow::m_translate [private]
flag to indicate if the Right mouse button is pressed when dragging
Definition at line 90 of file GLWindow.h.
Obstacle* GLWindow::obstacle [private]
a sphere obstacle within the boid space
Definition at line 130 of file GLWindow.h.
The documentation for this class was generated from the following files:
GLWindow.h
GLWindow.cpp