YOURPROJECTNAMEGOESHERE: Flock Class Reference
Flock Class Reference
#include <flock.h>
Public Member Functions
Flock (ngl::BBox *bbox, Obstacle *obstacle)
ctor
~Flock ()
dtor
void addBoids ()
add new boids
void removeBoids ()
removes the last 10 boids
void resetBoids ()
creates the boids.
void draw (const std::string &_shaderName, ngl::TransformStack &_transformStack, ngl::Camera *_cam) const
our flock draw function
void validateBoundingBoxCollision ()
our function to do the bounding box collision between the boids and the box.
void checkCollisions ()
a function to caclulate if the collision is true.
ngl::Vector finalFlockVelocity ()
a function to calculate the final velocity for the flock.
void update ()
the update method to do all the updates. Then the update is called in the GLWindow in the time event.
int getFlockSize ()
GUI related functions.
void setFlockSize (int size)
void setBoidSize (double size)
void setColour (ngl::Colour colour)
void setWireframe (bool value)
void setSimDistance (double distance)
void setSimFlockDistance (double distance)
void setSimCohesion (double cohesion)
void setSimSeparation (double separation)
void setSimAlignment (double alignment)
Private Member Functions
void loadMatricesToShader (ngl::TransformStack &_tx, ngl::Camera *_cam) const
shader method
void checkSphereCollisions ()
our sphere collision method.
bool sphereSphereCollision (ngl::Vector _pos1, GLfloat _radius1, ngl::Vector _pos2, GLfloat _radius2)
do the actual sphereSphere collisions
Private Attributes
std::vector< Boid * > m_boidList
a dynamic array to contain the boids.
bool m_hit
int m_numberOfBoids
the number of boids are created
Flock * m_react
pointer to object of Behaviour class
bool m_checkSphereSphere
flag to indicate if we need to do spheresphere checks
int _boidId
variable to store the boid count
Boid * _boid
pointer to boid class.
ngl::BBox * m_bbox
a pointer to the bbox.
Obstacle * m_obstacle
a pointer for the obstacle class
Behaviours * m_behaviours
a pointer for the behaviour class
double m_boidScale
ngl::Colour m_boidColour
variable to store the color of the boid.
Detailed Description
Definition at line 23 of file flock.h.
Constructor & Destructor Documentation
Flock::Flock (ngl::BBox * bbox, Obstacle * obstacle)
ctor
Definition at line 12 of file flock.cpp.
References m_bbox, m_behaviours, m_checkSphereSphere, m_numberOfBoids, m_obstacle, and resetBoids().
{
    m_behaviours = new Behaviours();
    m_bbox = bbox;
    m_numberOfBoids = 200;
    m_checkSphereSphere=true;
    m_obstacle = obstacle;
    resetBoids();
}
Flock::~Flock ()
dtor
Member Function Documentation
void Flock::addBoids ()
add new boids
Definition at line 64 of file flock.cpp.
References m_boidList, m_numberOfBoids, and s_extents.
{
    if (m_numberOfBoids <= 1990)
    {
        ngl::Random *rng=ngl::Random::instance();
        ngl::Vector dir;
        dir=rng->getRandomVector();
        // add the spheres to the end of the particle list
        for(int i=0; i<10; i++)
        {
            //std::cout<<"adding boid"<<endl;
            m_boidList.push_back(new Boid(rng->getRandomPoint(s_extents,s_extents,s_extents),dir));
            ++m_numberOfBoids;
        }
    }
}
void Flock::checkCollisions ()
a function to caclulate if the collision is true.
Definition at line 294 of file flock.cpp.
References checkSphereCollisions(), m_checkSphereSphere, and validateBoundingBoxCollision().
{
    if(m_checkSphereSphere == true)
    {
        checkSphereCollisions();
    }
    validateBoundingBoxCollision();
}
void Flock::checkSphereCollisions () [private]
our sphere collision method.
end of citation
Definition at line 254 of file flock.cpp.
References Obstacle::getSpherePosition(), Obstacle::getSphereRadius(), m_boidList, m_obstacle, and sphereSphereCollision().
{
    bool collide;
    unsigned int size=m_boidList.size();
    {
        for(unsigned int Current=0; Current<size; ++Current)
        {
            if(Current)
            {
                collide =sphereSphereCollision(
                            m_boidList.at(Current)->getPosition(),m_boidList.at(Current)->getSize(),
                            m_obstacle->getSpherePosition(),m_obstacle->getSphereRadius() * 3.0
                            );
                if(collide)
                {
                    m_boidList.at(Current)->reverse();
                    m_boidList.at(Current)->setHit();
                    ngl::Vector v = m_boidList.at(Current)->getPosition() - m_obstacle->getSpherePosition();
                    GLfloat l = v.length();
                    if (l <m_obstacle->getSphereRadius())
                    {
                        m_boidList.at(Current)->setPosition(v * (m_obstacle->getSphereRadius() - l));
                        v.normalize();
                    }
                }
            }
        }
    }
}
void Flock::draw (const std::string & _shaderName, ngl::TransformStack & _transformStack, ngl::Camera * _cam) const
our flock draw function
Definition at line 24 of file flock.cpp.
References Boid::draw(), loadMatricesToShader(), and m_boidList.
{
    ngl::ShaderLib *shader=ngl::ShaderLib::instance();
    shader->use(_shaderName);
    _transformStack.pushTransform();
    loadMatricesToShader(_transformStack, _cam);
    BOOST_FOREACH(Boid *b, m_boidList)
    {
        b->draw(_shaderName,_transformStack,_cam);
    }
    _transformStack.popTransform();
    glPolygonMode(GL_FRONT_AND_BACK,GL_FILL);
}
ngl::Vector Flock::finalFlockVelocity ()
a function to calculate the final velocity for the flock.
int Flock::getFlockSize () [inline]
GUI related functions.
Definition at line 58 of file flock.h.
References m_numberOfBoids.
{return m_numberOfBoids;}
void Flock::loadMatricesToShader (ngl::TransformStack & _tx, ngl::Camera * _cam) const [private]
shader method
Definition at line 43 of file flock.cpp.
{
    ngl::ShaderLib *shader = ngl::ShaderLib::instance();
    ngl::Matrix MV;
    ngl::Matrix MVP;
    ngl::Mat3x3 normalMatrix;
    ngl::Matrix M;
    M = _tx.getCurrentTransform().getMatrix();
    MV = _tx.getCurrAndGlobal().getMatrix() *_cam->getViewMatrix();
    MVP = MV * _cam->getProjectionMatrix();
    normalMatrix = MV;
    normalMatrix.inverse();
    shader->setShaderParamFromMatrix("MV", MV);
    shader->setShaderParamFromMatrix("MVP", MVP);
    shader->setShaderParamFromMat3x3("normalMatrix", normalMatrix);
    shader->setShaderParamFromMatrix("M", M);
}
void Flock::removeBoids ()
removes the last 10 boids
Definition at line 83 of file flock.cpp.
References m_boidList, and m_numberOfBoids.
{
    if (m_numberOfBoids > 10)
    {
        for (int i = 0; i < 10; i++)
        {
            m_boidList.pop_back();
            --m_numberOfBoids;
        }
    }
}
void Flock::resetBoids ()
creates the boids.
Definition at line 95 of file flock.cpp.
References m_boidList, m_numberOfBoids, and s_extents.
{
    m_boidList.clear();
    ngl::Vector dir;
    ngl::Random *rng=ngl::Random::instance();
    for(int i=0; i<m_numberOfBoids; ++i)
    {
        dir=rng->getRandomVector();
        m_boidList.push_back(new Boid(rng->getRandomPoint(s_extents,s_extents,s_extents),dir));
    }
}
void Flock::setBoidSize (double size)
Definition at line 126 of file flock.cpp.
References m_boidList, and Boid::setScale().
{
    BOOST_FOREACH(Boid *s,m_boidList)
    {
        s->setScale(size);
    }
}
void Flock::setColour (ngl::Colour colour)
Definition at line 134 of file flock.cpp.
References m_boidList, and Boid::setColour().
{
    BOOST_FOREACH(Boid *s,m_boidList)
    {
        s->setColour(colour);
    }
}
void Flock::setFlockSize (int size) [inline]
Definition at line 59 of file flock.h.
References m_numberOfBoids.
{m_numberOfBoids = size;}
void Flock::setSimAlignment (double alignment)
Definition at line 170 of file flock.cpp.
References m_behaviours, and Behaviours::setAlignment().
{
    m_behaviours->setAlignment(alignment);
}
void Flock::setSimCohesion (double cohesion)
Definition at line 160 of file flock.cpp.
References m_behaviours, and Behaviours::setCohesionForce().
{
    m_behaviours->setCohesionForce(cohesion);
}
void Flock::setSimDistance (double distance)
Definition at line 150 of file flock.cpp.
References m_behaviours, and Behaviours::setBehaviourDistance().
{
    m_behaviours->setBehaviourDistance(distance);
}
void Flock::setSimFlockDistance (double distance)
Definition at line 155 of file flock.cpp.
References m_behaviours, and Behaviours::setFlockDistance().
{
    m_behaviours->setFlockDistance(distance);
}
void Flock::setSimSeparation (double separation)
Definition at line 165 of file flock.cpp.
References m_behaviours, and Behaviours::setSeparationForce().
{
    m_behaviours->setSeparationForce(separation);
}
void Flock::setWireframe (bool value)
Definition at line 142 of file flock.cpp.
References m_boidList, and Boid::setWireframe().
{
    BOOST_FOREACH(Boid *s,m_boidList)
    {
        s->setWireframe(value);
    }
}
bool Flock::sphereSphereCollision (ngl::Vector _pos, GLfloat _rad, ngl::Vector _pos1, GLfloat _rad1) [private]
do the actual sphereSphere collisions
end of Citation
Parameters:
[in] _pos1 the position of the first sphere
[in] _radius1 the radius of the first sphere
[in] _pos2 the position of the second sphere
[in] _radius2 the radius of the second sphere
The following section is modified from :- John Macey(2011).Collisions Example, BoundingBox. [Accessed 2012] Available from: bzr branch http://nccastaff.bournemouth.ac.uk/jmacey/Code/Collisions
Definition at line 224 of file flock.cpp.
{
    // the relative position of the spheres
    ngl::Vector relPos;
    //min an max distances of the spheres
    GLfloat dist;
    GLfloat minDist;
    GLfloat len;
    relPos =_pos-_pos1;
    // and the distance
    len=relPos.length();
    dist=len*len;
    minDist =_rad+_rad1;
    // if it is a hit
    if(dist <=(3 * (minDist * minDist)))
    {
        return true;
    }
    else
    {
        return false;
    }
}
void Flock::update ()
the update method to do all the updates. Then the update is called in the GLWindow in the time event.
Definition at line 108 of file flock.cpp.
References Behaviours::Alignment(), Behaviours::BehaviourSetup(), Boid::boidDirection(), checkCollisions(), Behaviours::Cohesion(), Behaviours::Destination(), m_behaviours, m_boidList, Behaviours::Seperation(), Boid::updateVelocity(), and Boid::velocityConstraint().
{
    checkCollisions();
    int count = 0;
    BOOST_FOREACH(Boid *s,m_boidList)
    {
        m_behaviours->Cohesion(count, m_boidList);
        m_behaviours->Alignment(count, m_boidList);
        m_behaviours->Seperation(count, m_boidList);
        m_behaviours->Destination(count,m_boidList);
        s->updateVelocity(m_behaviours->BehaviourSetup());
        s->velocityConstraint();
        s->boidDirection();
        count++;
    }
}
void Flock::validateBoundingBoxCollision ()
our function to do the bounding box collision between the boids and the box.
The following section is modified from :- John Macey(2011).Collisions Example, BoundingBox. [Accessed 2012] Available from: bzr branch http://nccastaff.bournemouth.ac.uk/jmacey/Code/Collisions
Definition at line 179 of file flock.cpp.
References Boid::getNextPosition(), Boid::getPosition(), Boid::getSize(), Boid::getVelocity(), Boid::isHit(), m_bbox, m_boidList, and Boid::setVelocity().
{
    //create an array of the extents of the bounding box
    float ext[6];
    ext[0]=ext[1]=(m_bbox->height()/2.0f);
    ext[2]=ext[3]=(m_bbox->width()/2.0f);
    ext[4]=ext[5]=(m_bbox->depth()/2.0f);
    // Dot product needs a Vector so we convert The Point Temp into a Vector so we can
    // do a dot product on it
    ngl::Vector point;
    // D is the distance of the Agent from the Plane. If it is less than ext[i] then there is
    // no collision
    GLfloat Distance;
    // Loop for each sphere in the vector list
    BOOST_FOREACH(Boid *s, m_boidList)
    {
        point=s->getPosition();
        //Now we need to check the Sphere agains all 6 planes of the BBOx
        //If a collision is found we change the dir of the Sphere then Break
        for(int i=0; i<6; ++i)
        {
            //to calculate the distance we take the dotporduct of the Plane Normal
            //with the new point P
            Distance=m_bbox->getNormalArray()[i].dot(point);
            //Now Add the Radius of the sphere to the offsett
            Distance+=s->getSize();
            // If this is greater or equal to the BBox extent /2 then there is a collision
            //So we calculate the Spheres new direction
            if(Distance >=ext[i])
            {
                //We use the same calculation as in raytracing to determine the
                // the new direction
                GLfloat x= 2*( s->getVelocity().dot((m_bbox->getNormalArray()[i])));
                ngl::Vector d =m_bbox->getNormalArray()[i]*x;
                s->setVelocity(s->getNextPosition()-d * 5.0);
                s->isHit();
            }//end of hit test
        }//end of each face test
    }//end of for
}
Member Data Documentation
Boid* Flock::_boid [private]
pointer to boid class.
Definition at line 90 of file flock.h.
int Flock::_boidId [private]
variable to store the boid count
Definition at line 87 of file flock.h.
ngl::BBox* Flock::m_bbox [private]
a pointer to the bbox.
Definition at line 93 of file flock.h.
Behaviours* Flock::m_behaviours [private]
a pointer for the behaviour class
Definition at line 105 of file flock.h.
ngl::Colour Flock::m_boidColour [private]
variable to store the color of the boid.
Definition at line 110 of file flock.h.
std::vector<Boid*> Flock::m_boidList [private]
a dynamic array to contain the boids.
Definition at line 72 of file flock.h.
double Flock::m_boidScale [private]
Definition at line 107 of file flock.h.
bool Flock::m_checkSphereSphere [private]
flag to indicate if we need to do spheresphere checks
Definition at line 84 of file flock.h.
bool Flock::m_hit [private]
flag to indicate if the sphere has been hit by ray
Definition at line 75 of file flock.h.
int Flock::m_numberOfBoids [private]
the number of boids are created
Definition at line 78 of file flock.h.
Obstacle* Flock::m_obstacle [private]
a pointer for the obstacle class
Definition at line 102 of file flock.h.
Flock* Flock::m_react [private]
pointer to object of Behaviour class
Definition at line 81 of file flock.h.
The documentation for this class was generated from the following files:
flock.h
flock.cpp